# Generated by Django 5.1.2 on 2024-10-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_album_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
